audit_header: false
title: "North County Real Estate Careers"
description: Jim Crotwell, a top Real Estate Agent in Orange County, shares his own internal real estate agent training for free. His Real Estate Training, Tips and Advice will help you sell more homes in less time.
show_custom_links: false
custom_links:
  - title:
    url:

client:
  name: Jim Crotwell
  title:
  license_number: 'DRE #01851267'
  about_markdown: |
    I transitioned into the Real Estate industry in 2004. I began my real estate career as a Sales Rep for Southland Title in North Orange County and built a Top Producing Sales Team. In 2008 I became the North Orange County Sales Manager for Century 21 Superstars/Award and in 2010 moved to Keller Williams Pacific Estates (Long Beach, CA) and worked as the Lead Buyers Agent for the #1 Top Producing Team. In 2013 I became the Team Leader for Keller Williams Whittier and by 2017 recruited over 200 agents and built the market center into the #1 office in the entire area in market share and total production as well as home of six of the Top Ten agents in the area. Currently I am the Team Leader at the Keller Williams Carlsbad/North San Diego County market center.
  market: Orange County
  brand: Keller Williams Realty Carlsbad
  brokerage:
  address: '6005 Hidden Valley Road, #200<br>Carlsbad, CA 92011'
  phone: 760-496-3920
  phone_type:
  phone2:
  phone2_type:
  email: JimCrotwell@kw.com
  url: http://jimcrotwell.com

sidebar_CTA:
  - CTA_image_path: /img/cta-images/001.jpg
    CTA_title: "Looking to Build Your Real Estate Career?"
    CTA_text: "Let's talk about how Keller Williams Realty Carlsbad can take your business to new heights."
    CTA_link_text: "Free Strategy Session"
    CTA_url: /contact/

# second_sidebar_CTA:
#   - CTA_image_path2: /img/cta-images/002.jpg
#     CTA_title2: "Join Our Team"
#     CTA_text2: "Sell more homes by joining forces with the our dynamic real estate company."
#     CTA_link_text2: "Career Info"
#     CTA_url2: /

lender:
  show_section: false
  header_text: Preferred Lender
  headshot_path: http://fillmurray.com/200/200
  logo_path: /img/logo.png
  logo_path_2:
  name: Bill Murray
  brand: Lender Co.
  phone: 555-555-5555
  email: bill@murray.com
  url: http://eyegoop.com

socials:
  review_sm_icons: false
  facebook_url: https://www.facebook.com/kellerwilliamscarlsbad/
  linkedin_url:
  gplus_url:
  youtube_url:
  twitter_url:
  instagram_url:
  pinterest_url:
  zillow_url:
  trulia_url:
  yelp_url:
  podcast_url:

podcast:
  title: 'Orange County Real Estate Podcast with Jim Crotwell'
  categories: Education
  image: /img/podcast.jpg
  subtitle: 'Learn all the tips, tricks and more for buyers and sellers in the Orange County Area Real Estate Market'
  description: 'If you are looking to buy or sell a home, get all the information and the latest updates, tips, and tricks from Keller Williams Realty Carlsbad - your professional Orange County Real Estate Agents.'
  keywords: 'Real Estate for sale, Real Estate agents, top real estate agents, local real estate agents, find a real estate agent, houses for sale in Orange County, home selling tips, home for sale, home buying, home buying process, property finder, property search, property, real estate market, estate agent, realestate, real estate listings, buying a house, homes for sale, mls, home buyer'
  author: 'Jim Crotwell'

images:
  client_headshot_path: /img/headshot.jpg
  hero_logo_path: /img/logo.png
  logo_width_number: 40
  hero_text: Orange County Real Estate Video Blog
  hero_background_hex: '#999'
  hero_image_path: /img/background.jpg
  post_cover: /img/cover.jpg
site_colors:
  brand_color: '#b40101'
  theme_color: '#999'
  theme_text_color: '#5d9bd3'
  main_body_color: '#ffffff'
  main_body_text_color: '#353535'

navbar_colors:
  border_bottom:

header_shadow:
  h_shadow: 0px
  w_shadow: 2px
  shadow_spread: 7px
  shadow_color: transparent

buttons:
  button_radius_number: 0
  button_padding_width_number: 10
  button_padding_height_number: 15
  button_border_color: '#ffffff'
  button_background_color: transparent
  button_text_color: '#123456'
  secondary_button_border_color: '#ffffff'
  secondary_button_background_color: 'rgba(0, 0, 0, 0)'
  secondary_button_text_color: '#ffffff'
